### PR TITLE
Add models

### PR DESCRIPTION
**Pull request by ngkiencuong**
- Add models to store and edit the Pretext and Posttext
- #2 
- #6

### CODE REVIEW

**Comment by euroblaze** [comment]
@simplify-m97 merge and update demo please. Thanks

**Comment by simplify-m97** [comment]
@ngkiencuong 

Like this, you are overwriting the print option from sales, which is incorrect.

Please create print options for invoices.

**Comment by ngkiencuong** [comment]
> @ngkiencuong
> 
> Like this, you are overwriting the print option from sales, which is incorrect.
> 
> Please create print options for invoices.

I'm sorry. It's my bad. Let me fix it.

**Comment by ngkiencuong** [comment]
@simplify-m97 I fixed it.

**Comment by simplify-m97** [comment]
One more thing like this do we need the quotation_print_option in the __manifest__ is anything depending on it?

**Comment by ngkiencuong** [comment]
> One more thing like this do we need the quotation_print_option in the **manifest** is anything depending on it?

That's the thing I'm wondering. Both quotation_print_options and invoice_printoptions inherit a report template in the l10n_de module. I think I messed it up a little bit. I'm about to check and fix it.

**Comment by euroblaze** [comment]
Yes, would be really better if the two PrintOptions modules remain
separate, and installable separately.

@ngkiencuong what is the name of the shared module?

**Comment by ngkiencuong** [comment]
> Yes, would be really better if the two PrintOptions modules remain separate, and installable independently. @ngkiencuong what is the name of the shared module?

It's l10n_de.

**Comment by euroblaze** [comment]
> Nguyen Cuong:
I suggest splitting the code of quotation_print_options module into two separate modules: one is for the quotation print options and the other is for custom the layout report. Because many reports inherit the layout, not only the quotation, it can be invoice, purchase,... We should keep the custom layout module as a shared module.

> Ashant Chalasani:
I am open to that, but Cuong, there are 150+ open tickets and customers are breathing down our neck.
So it seems to me that it would be safe to run that list down to near-0, start with the v17 upgrades (in Autumn), and at that time, consider these important restructring/refactorings.

> Ashant Chalasani:
As for the custom layout report, IMO we should standardise the layouts to ALL customers of PowerOn™, and not give them much choice for customisation, at least at this point in time.

As long as the reports (particularly invoice) is adhering to the legal and business norms in this part of the world, customers don’t seek choice. Standardized PDFs are OK.

I do like the idea of separating customer-layout-report and print-options (qpo, ipo, and possibly also delivery notes).

> Ashant Chalasani:
Cuong, can we start work on ipo?

> Nguyen Cuong:
I did. But that's what I concern about our code of modules. So is it right to say that every customers have QPO will also have IPO?

> Ashant Chalasani:
Unofficially yes.
Officially no, because we want to keep the modules separated/independent.

> Nguyen Cuong:
My solution is the best way to keep QPO and IPO separated. Otherwise, I have to make IPO depends on QPO (just for now). That means when you install IPO, it will automatically install QPO. If you already had QPO be installed, the IPO will be installed normally.

> Ashant Chalasani:
> My solution is the best way to keep QPO and IPO separated.

Agree and understand.
But we don’t have the time to dedicate to this task, for the moment.

> Otherwise, I have to make IPO depends on QPO (just for now). That means when you install IPO, it will automatically install QPO. If you already had QPO be installed, the IPO will be installed normally.

OK, customers can live with that compromise for now.

**Pull request merged**
