### PR TITLE
Fix the issue #2

### PR DESCRIPTION
**Pull request by ngkiencuong**
#2

### CODE REVIEW

**Comment by euroblaze** [comment]
@ngkiencuong 

- where can the Pretext and Posttext **templates** be edited (and stored for reuse)?

**Comment by ngkiencuong** [comment]
> @ngkiencuong
> 
> * where can the Pretext and Posttext **templates** be edited (and stored for reuse)?

It's not yet available to store and edit the Pretext and Posttext.

**Comment by euroblaze** [comment]
On Wed 5. Jul 2023 at 19:06, 'ngkiencuong' via euroblaze Github Common
Account ***@***.***> wrote:

> @ngkiencuong <https://github.com/ngkiencuong>
>
>    - where can the Pretext and Posttext *templates* be edited (and stored
>    for reuse)?
>
> It's not yet available to store and edit the Pretext and Posttext.
>

This would be a necessary enhancement then.
Can you proceed to implement @ngkiencuong?

>

**Comment by ngkiencuong** [comment]
> This would be a necessary enhancement then. Can you proceed to implement @ngkiencuong?

Yes. It won't take a long time. Can be done tomorrow.

**Comment by euroblaze** [comment]
Yes. It won't take a long time. Can be done tomorrow.
>

Tomorrow is OK.

**Pull request merged**
